### ISSUE TITLE
Any chance making a "Copy Unicode URL" extension for Firefox as well?

### ISSUE THREAD

**Issue by ericgl** [ilyaigpetrov/copy-unicode-urls#16]
Hi,
Any chance to have "Copy Unicode URL" for Firefox as well?
I'm annoyed by those percent-encoded URLs. Happens all the time, even with URLs that contain only Latin characters. 

A simple "Copy URL (Decoded)" in the right-click menu would be nice.

Thanks ion advance,
Eric

**Comment by ilyaigpetrov** [comment]
Please, test: https://addons.mozilla.org/en-US/firefox/addon/copy-unicode-urls.
Feedback is welcome.

**Comment by ericgl** [comment]
Just tested in Firefox 99. 
The option appears in the context menu (Copy Unicode URLs). Within it, there are 2 options.

It doesn't work. URLs that are percent-encoded still get copied as percent-encoded.

**Comment by ilyaigpetrov** [comment]
Could you, please, share a link/page for testing?
I can't reproduce in my case.

**Comment by ilyaigpetrov** [comment]
1) I search this in Google: https://www.google.com/search?q=телеком-
тв.рф+Установка+эфирных+антенн+в+Москве+и+МО.
2) If you right click it and copy the link (not via extension) then you get:

https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&cad=rja&uact=8&ved=2ahUKEwjPv7Xb_ZD3AhXpsYsKHR6zD6MQFnoECAUQAQ&url=http%3A%2F%2Fxn----dtbhazejp5ah.xn--p1ai%2F%25D1%2583%25D1%2581%25D1%2582%25D0%25B0%25D0%25BD%25D0%25BE%25D0%25B2%25D0%25BA%25D0%25B0-%25D1%258D%25D1%2584%25D0%25B8%25D1%2580%25D0%25BD%25D1%258B%25D1%2585-%25D0%25B0%25D0%25BD%25D1%2582%25D0%25B5%25D0%25BD%25D0%25BD%2F&usg=AOvVaw02uOihXZS2HdVzOAS1dWBh

Mind that there are lots of %25 which is an encoded symbol "%". So it is
double encoded.

3) If you copy url via the extension then you get:

https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&cad=rja&uact=8&ved=2ahUKEwjPv7Xb_ZD3AhXpsYsKHR6zD6MQFnoECAUQAQ&url=http%3A%2F%2Fxn----dtbhazejp5ah.xn--p1ai%2F%D1%83%D1%81%D1%82%D0%B0%D0%BD%D0%BE%D0%B2%D0%BA%D0%B0-%D1%8D%D1%84%D0%B8%D1%80%D0%BD%D1%8B%D1%85-%D0%B0%D0%BD%D1%82%D0%B5%D0%BD%D0%BD%2F&usg=AOvVaw02uOihXZS2HdVzOAS1dWBh

Mind that there are much less %25, this url is encoded once, not double,
because we decoded it one time.

Conclusion:
- Google outputs double encoded links, our extension decodes them only
once, finally you get a one time encoded string.

I haven't yet decided if to add an option to decode an url till it can't be
decoded anymore.

**Comment by ilyaigpetrov** [comment]
Please, test: [copy-unicode-urls-0.0.19-rc0.zip](https://github.com/ilyaigpetrov/copy-unicode-urls/files/8529893/copy-unicode-urls-0.0.19-rc0.zip).

1) Unzip the archive.
2) Open about:debugging ->This Firefox.
3) Load temporary add-on
4) Point to `manifest.json` file from the unpacked archive.
5) Right click on the icon and check "If to decode multiple times".
6) Test your case.

**Comment by ilyaigpetrov** [comment]
This option breaks linkification of gmail:
![copy-unicode-urls-broken-link](https://user-images.githubusercontent.com/1090811/164433708-b28f3061-bac5-4272-9f91-a13ba28e7866.png)

**Comment by ericgl** [comment]
"This option breaks linkification of gmail"
So I'll skip **v0.0.19 RC0**. I'm guessing you're going to release a newer version which will NOT break links in Gmail?

**Comment by ilyaigpetrov** [comment]
> I'm guessing you're going to release a newer version which will NOT break links in Gmail?

The only way to get it not to break is to percent-encode the url.

**Comment by ilyaigpetrov** [comment]
Or to knock the gmail team door and be very persuasive.

**Comment by ericgl** [comment]
Well, like I said in a previous post, I found a Firefox extension that does work (decodes percent-encoded URLs):
https://addons.mozilla.org/en-US/firefox/addon/copy-true-link/
Just not sure if the permission to "Access your data for all websites" is really required.

**Comment by ilyaigpetrov** [comment]
What's your use case? Do you really need just to copy urls from google's search results?

**Comment by ericgl** [comment]
Sometimes I need to save a URL in a text document, and I just want the exact characters, not the percent-encoded gibberish.

**Comment by ilyaigpetrov** [comment]
I'm afraid it's an issue on Google's side. You may try sending them link to this message via their feedback form.
![gmail-linkification](https://user-images.githubusercontent.com/1090811/164501917-40958447-9126-4fcb-aba6-becbea68d852.png)

**Comment by ericgl** [comment]
Thanks anyway, I appreciate your efforts.
