### ISSUE TITLE
How to generate crx file?

### ISSUE THREAD

**Issue by zhang13690** [ilyaigpetrov/copy-unicode-urls#9]
Because Chinese mainland can not visit Google application store website, can you provide a CRX files for installation? 
Or how to generate a CRX file?
Thanks.

**Comment by ilyaigpetrov** [comment]
As far as I know CRX are just zip files so you may use one instead of another freely.
Take a look at releases section: https://github.com/ilyaigpetrov/copy-unicode-urls/releases.
Be aware that extensions installed from file system are not updated automatically so you will have to manually install new version when it becomes published.

**Comment by zhang13690** [comment]
Thank you. 
By the way, I want to create a pull request for adding chinese support later, please check it.

**Comment by ilyaigpetrov** [comment]
Hey, @zhang13690, today I found out that the version from the latest zip archive was broken (because it was non-persistent). I fixed this #13 bug in the latest testing release: https://github.com/ilyaigpetrov/copy-unicode-urls/releases/tag/0.0.16. Now it should work. Enjoy.
